const ROUTES = {
  Walkthrough: 'Walkthrough',
  Login: 'Login',
  LoginForgotPassword: 'LoginForgotPassword',
  LoginRecoveryPassword: 'LoginRecoveryPassword',
  LoginUpdatedPassword: 'LoginUpdatedPassword',
  RegisterAccount: 'RegisterAccount',
  SelectPlan: 'SelectPlan',
  RecipeDetail: 'RecipeDetail',
  NutritionDetail: 'NutritionDetail',
  SeeAllTips: 'See All Tips',
  BoxSummary: 'BoxSummary',
  AddDeliveryAddress: 'AddDeliveryAddress',
  Checkout_SelectDeliveryAddress: 'Checkout',
  PersonalInformation: 'PersonalInformation',
  Checkout_PaymentMethod: 'Checkout_PaymentMethod',
  SelectCreditCard: 'SelectCreditCard',
  AddNewCard: 'AddNewCard',
  OrderCompleted: 'OrderCompleted',
  Upcoming: 'Upcoming',
  OrderDetail: 'OrderDetail',
  OrderCalendar: 'OrderCalendar',
  Explorer: 'Explorer',
  Explorer_OnTheMenu: 'Explorer_OnTheMenu',
  Explorer_CookBook: 'Explorer_CookBook',
  Explorer_ListView: 'Explorer_ListView',
  Explorer_CookBook_RecipeDetail: 'Explorer_CookBook_RecipeDetail',
  Explorer_SavedRecipe: 'Explorer_SavedRecipe',
  Explorer_PreviousCooked: 'Explorer_PreviousCooked',
  Explorer_Search: 'Explorer_Search',
  Explorer_SearchResult: 'Explorer_SearchResult',
  VirtualChef: 'VirtualChef',
  VirtualChef_ListRecipes: 'VirtualChef_ListRecipes',
  Community: 'Community',
  CommunityTab: 'CommunityTab',
  Daily: 'Daily',
  Nutrition: 'Nutrition',
  TipsAndTechniques: 'TipsAndTechniques',
  LifeStyle: 'LifeStyle',
  NewsNutritionList: 'NewsNutritionList',
  NewsNutritionDetail: 'NewsNutritionDetail',
  Profile: 'Profile',
  MyProfile: 'MyProfile',
  MyProfileEdit: 'MyProfileEdit',
  ProfileOrderHistory: 'ProfileOrderHistory',
  ProfileOrderHistoryDetail: 'ProfileOrderHistoryDetail',
  ProfileMyAddress: 'ProfileMyAddress',
  ProfileAddNewAddress: 'ProfileAddNewAddress',
  ProfilePaymentMethod: 'ProfilePaymentMethod',
  ProfileSaveArticle: 'ProfileSaveArticle',
  ProfileInvite: 'ProfileInvite',
  ProfileSettings: 'ProfileSettings',
  Filter: 'Filter',
  SignUpPaymentMethod: 'SignUpPaymentMethod',
};

export default ROUTES;
